# Generated by Django 4.0.2 on 2022-09-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('Mother_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Class', models.IntegerField()),
                ('Contact_number', models.IntegerField()),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
    ]
